### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by javiermortiz** [ycherradi/remorph-project#1]
Hi Yassine, here are some comments about your docs:

MVP list
- [x] Campaigns and profile are good, but I strongly believe you should add contributions and rewards as your 5th and 6th  instead of search, categories, and follows. Contributions and rewards are foundational to the purpose of the site.

DB Schema
- [x] Campaigns categories relationship should be many to one instead of one to many as many campaigns can belong to the same category.
- [x] I think I'd add the campaignId to the rewards table so that is easier to associate the reward to a campaign. 
- How do you plan on using the bank account table?

**Comment by ycherradi** [comment]
Hi Javier, 
Thank you for the feedback.

for the MVP list I will make the recommended changes.
However, for the DB Schema I have added the campaignId to the rewards table but I am not sure on how to implement the recommendation regarding the categories relationship to campaigns. I have the categoryId listed under the campaigns table so that I can have a dropdown to select which category is the campaign when starting a new campaign. 
I have changed the campaigns relationship to belong to same category I think as you recommended.
Can you please review it and let me know?

Thank you
Yassine Cherradi

**Comment by ycherradi** [comment]
Hi Javier,

After discussing the issue with Brian, I have made the necessary changes that will work for what I want and he did approve it.

Thank You
Yassine Cherradi
